project_name: threaded-top-reporter

builds:
  - id: threaded-top-reporter
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -X main.Version={{.Version}}
