name: Release on Tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # (Optional) Import GPG key for signed artifacts
      # - name: Import GPG key
      #   uses: crazy-max/ghaction-import-gpg@v6
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase:     ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If using Pro:
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          # If you import GPG above:
          # GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
